name: Export Android APK

on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Godot and export Android APK
        uses: rannek/godot-export@v5
        with:
          godot-version: '4.2.1'
          export-template-version: '4.2.1'
          export-platform: 'Android'
          output-dir: 'build'
          output-name: 'game.apk'
          godot-executable: godot

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/game.apk
