name: Export Godot Android Build

on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export Android APK
        uses: dulvui/godot-android-export@v4.1.0
        with:
          godot-version: '4.2.1'  # Reemplaza con la versión de Godot que estés utilizando
          working-directory: '.'  # Directorio donde se encuentra tu archivo project.godot

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: game-apk
          path: build/android/game.apk
